### ISSUE TITLE
MAKE A CROSS BUTTON ON RIGHT SIDE OF TASK SO ON CLICKING ON IT THE TASK SHOWS TO BE DONE 


### ISSUE THREAD

**Issue by draunger** [draunger/TO-DO-LIST#3]
On clicking the cross button it shown like this 
![Screenshot_2024-03-05-00-13-43-137_com.google.android.googlequicksearchbox.jpg](https://github.com/draunger/TO-DO-LIST/assets/145993709/c2599158-091f-4053-a588-39b25c38c026)

**Comment by manav6262** [comment]
assign me
